import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class RecipeService {
  recipes = [
    {
      id: 1,
      name: 'Honey Chipotle Chicken Skewers',
      type: 'Non-Veg',
      cookTime: '30 minutes',
      difficulty: 'Easy',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Honey-Chipotle-Chicken-Skewers-1.jpg',
      ingredients: [
        '1 lb boneless, skinless chicken breasts, cut into 1-inch pieces',
        '1/2 cup honey',
        '1/4 cup lime juice',
        '2 tablespoons chipotle chili powder',
        '1 teaspoon garlic powder',
        '1/2 teaspoon salt',
        'Wooden skewers, soaked in water for 30 minutes',
      ],
      steps: [
        'In a large bowl, combine the chicken, honey, lime juice, chipotle chili powder, garlic powder, and salt. Stir to coat the chicken evenly.',
        'Thread the chicken pieces onto the soaked wooden skewers.',
        'Grill the skewers over medium-high heat for 8-10 minutes, turning occasionally, until the chicken is cooked through.',
        'Serve immediately.',
      ],
    },
    {
      id: 2,
      name: 'Amazing Green Rice',
      type: 'Veg',
      cookTime: '45 minutes',
      difficulty: 'Moderate',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Amazing-Green-Rice-1.jpg',
      ingredients: [
        '1 cup uncooked white rice',
        '1 cup fresh spinach leaves',
        '1/2 cup fresh cilantro leaves',
        '1/4 cup green onions, chopped',
        '2 cloves garlic',
        '1 tablespoon olive oil',
        '1 teaspoon salt',
        '1/4 teaspoon black pepper',
        '1 1/2 cups water or broth',
      ],
      steps: [
        'In a blender or food processor, combine the spinach, cilantro, green onions, garlic, olive oil, salt, and pepper. Blend until smooth.',
        'In a medium saucepan, combine the rice, blended spinach mixture, and water or broth. Bring to a boil over high heat.',
        'Reduce heat to low, cover, and simmer for 20-25 minutes, or until the rice is tender and the liquid is absorbed.',
        'Fluff the rice with a fork and serve warm.',
      ],
    },
    {
      id: 3,
      name: 'Super Yummy Chicken Salad',
      type: 'Non-Veg',
      cookTime: '20 minutes',
      difficulty: 'Easy',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Super-Yummy-Chicken-Salad-1.jpg',
      ingredients: [
        '2 cups cooked chicken, shredded or chopped',
        '1/2 cup mayonnaise',
        '1/4 cup plain Greek yogurt',
        '2 tablespoons Dijon mustard',
        '1 tablespoon honey',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
        '1/2 cup grapes, halved',
        '1/2 cup celery, diced',
        '1/4 cup sliced almonds',
      ],
      steps: [
        'In a large bowl, combine the shredded chicken, mayonnaise, Greek yogurt, Dijon mustard, honey, salt, and black pepper. Mix well.',
        'Fold in the grapes, celery, and sliced almonds.',
        'Serve on bread, croissants, or lettuce leaves.',
      ],
    },
    {
      id: 4,
      name: 'Creamy Garlic Parmesan Chicken',
      type: 'Non-Veg',
      cookTime: '45 minutes',
      difficulty: 'Moderate',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Creamy-Garlic-Parmesan-Chicken-1.jpg',
      ingredients: [
        '4 boneless, skinless chicken breasts',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
        '2 tablespoons olive oil',
        '3 cloves garlic, minced',
        '1 cup heavy cream',
        '1/2 cup grated Parmesan cheese',
        '1/4 cup chicken broth',
        '1 teaspoon dried parsley',
        '1/2 teaspoon dried basil',
      ],
      steps: [
        'Season the chicken breasts with salt and black pepper.',
        'In a large skillet, heat the olive oil over medium-high heat. Add the chicken and cook for 5-7 minutes per side, or until golden brown and cooked through. Remove the chicken from the skillet and set aside.',
        'In the same skillet, sauté the minced garlic for 1 minute.',
        'Add the heavy cream, Parmesan cheese, chicken broth, dried parsley, and dried basil to the skillet. Whisk to combine and bring the mixture to a simmer.',
        'Return the chicken to the skillet and spoon the creamy sauce over the chicken. Simmer for 5-10 minutes, or until the sauce has thickened.',
        'Serve the chicken warm, garnished with additional Parmesan cheese and parsley if desired.',
      ],
    },
    {
      id: 5,
      name: 'Baked Feta Pasta',
      type: 'Veg',
      cookTime: '30 minutes',
      difficulty: 'Easy',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Baked-Feta-Pasta-1.jpg',
      ingredients: [
        '8 ounces uncooked pasta',
        '1 pint cherry tomatoes',
        '1 block (8 ounces) feta cheese',
        '1/4 cup olive oil',
        '3 cloves garlic, minced',
        '1/2 teaspoon dried oregano',
        '1/4 teaspoon red pepper flakes (optional)',
        'Salt and black pepper to taste',
        '1/2 cup fresh basil leaves, chopped',
      ],
      steps: [
        'Preheat the oven to 400°F (200°C).',
        'Cook the pasta according to package instructions. Drain and set aside.',
        'In a baking dish, arrange the cherry tomatoes around the edges. Place the block of feta cheese in the center.',
        'In a small bowl, combine the olive oil, minced garlic, dried oregano, and red pepper flakes (if using). Pour the mixture over the tomatoes and feta.',
        'Bake for 20-25 minutes, or until the tomatoes are bursting and the feta is softened.',
        'Remove the baking dish from the oven and use a fork to mash the feta and tomatoes together to create a sauce.',
        'Add the cooked pasta to the baking dish and toss to coat with the sauce.',
        'Season with salt and black pepper to taste.',
        'Garnish with fresh chopped basil leaves before serving.',
      ],
    },
    {
      id: 6,
      name: 'Healthy Chicken Burrito Bowls',
      type: 'Non-Veg',
      cookTime: '30 minutes',
      difficulty: 'Easy',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Healthy-Chicken-Burrito-Bowls-1.jpg',
      ingredients: [
        '1 lb boneless, skinless chicken breasts',
        '1 tablespoon olive oil',
        '1 tablespoon taco seasoning',
        '1 cup cooked brown rice',
        '1 can (15 oz) black beans, drained and rinsed',
        '1 cup corn kernels',
        '1 avocado, diced',
        '1/2 cup shredded cheddar cheese',
        '1/4 cup salsa',
        '2 tablespoons plain Greek yogurt',
      ],
      steps: [
        'Season the chicken breasts with the taco seasoning.',
        'In a large skillet, heat the olive oil over medium-high heat. Add the chicken and cook for 5-7 minutes per side, or until cooked through. Remove from heat and shred or chop the chicken.',
        'In a bowl, layer the cooked brown rice, shredded chicken, black beans, corn, avocado, cheddar cheese, salsa, and Greek yogurt.',
        'Serve immediately.',
      ],
    },
    {
      id: 7,
      name: 'Creamy Tuscan Garlic Chicken',
      type: 'Non-Veg',
      cookTime: '30 minutes',
      difficulty: 'Moderate',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Creamy-Tuscan-Garlic-Chicken-1.jpg',
      ingredients: [
        '4 boneless, skinless chicken breasts',
        '1 tablespoon olive oil',
        '3 cloves garlic, minced',
        '1 cup heavy cream',
        '1/2 cup grated Parmesan cheese',
        '1/2 cup sun-dried tomatoes, chopped',
        '1/4 cup fresh spinach leaves',
        '1 teaspoon dried basil',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
      ],
      steps: [
        'In a large skillet, heat the olive oil over medium-high heat. Add the chicken breasts and cook for 5-7 minutes per side, or until golden brown and cooked through. Remove the chicken from the skillet and set aside.',
        'In the same skillet, sauté the minced garlic for 1 minute.',
        'Add the heavy cream, Parmesan cheese, sun-dried tomatoes, spinach leaves, dried basil, salt, and black pepper to the skillet. Whisk to combine and bring the mixture to a simmer.',
        'Return the chicken to the skillet and spoon the creamy sauce over the chicken. Simmer for 5-10 minutes, or until the sauce has thickened and the spinach is wilted.',
        'Serve the chicken warm, garnished with additional Parmesan cheese and basil if desired.',
      ],
    },
    {
      id: 8,
      name: 'Healthy Chicken Salad Stuffed Avocados',
      type: 'Non-Veg',
      cookTime: '20 minutes',
      difficulty: 'Easy',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Healthy-Chicken-Salad-Stuffed-Avocados-1.jpg',
      ingredients: [
        '2 cups cooked chicken, shredded or chopped',
        '1/2 cup plain Greek yogurt',
        '2 tablespoons Dijon mustard',
        '1 tablespoon honey',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
        '1/2 cup grapes, halved',
        '1/2 cup celery, diced',
        '1/4 cup sliced almonds',
        '4 avocados, halved and pitted',
      ],
      steps: [
        'In a large bowl, combine the shredded chicken, Greek yogurt, Dijon mustard, honey, salt, and black pepper. Mix well.',
        'Fold in the grapes, celery, and sliced almonds.',
        'Scoop the chicken salad into the avocado halves.',
        'Serve immediately.',
      ],
    },
    {
      id: 9,
      name: 'Healthy Chicken Broccoli Alfredo',
      type: 'Non-Veg',
      cookTime: '30 minutes',
      difficulty: 'Easy',
      imageUrl:
        'https://pinchofyum.com/wp-content/uploads/Healthy-Chicken-Broccoli-Alfredo-1.jpg',
      ingredients: [
        '8 ounces uncooked pasta',
        '1 lb boneless, skinless chicken breasts, cut into bite-sized pieces',
        '1 tablespoon olive oil',
        '1 head broccoli, cut into florets',
        '1 cup low-fat milk',
        '1/2 cup grated Parmesan cheese',
        '2 tablespoons plain Greek yogurt',
        '2 cloves garlic, minced',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
      ],
      steps: [
        'Cook the pasta according to package instructions. Drain and set aside.',
        'In a large skillet, heat the olive oil over medium-high heat. Add the chicken and cook for 5-7 minutes, or until cooked through. Remove the chicken from the skillet and set aside.',
        'In the same skillet, add the broccoli florets and a splash of water. Cover and steam for 3-5 minutes, or until the broccoli is tender-crisp.',
        'In a blender or food processor, combine the low-fat milk, Parmesan cheese, Greek yogurt, minced garlic, salt, and black pepper. Blend until smooth.',
        'Return the cooked chicken to the skillet with the broccoli. Pour the creamy sauce over the chicken and broccoli and stir to combine.',
        'Add the cooked pasta to the skillet and toss to coat with the sauce.',
        'Serve warm.',
      ],
    },
  ];

  constructor() {}
}
